/* Program generated by bop2c */
/* Original circuit : watch.bop , Main = "Watch" */

#include <stdlib.h>
#include <stdio.h>

/* Reads a line of text from standard input into a buffer of given size.
   Returns 0 on success, and exit 1 on error. */
int readLineFromStdin(char* buffer, size_t bufferSize) {
  /* Read a line of text from standard input into the buffer. */
  size_t i = 0;
  int c = getchar();
  while (i < bufferSize-1 && c != '\n' && c != EOF) {
    buffer[i] = (char)c;
    i++;
    c = getchar();
  }
  buffer[i] = '\0';

  if (i == 0 && c == EOF) {
    exit(0);
  }

  if (i < bufferSize-1) {
    fprintf(stderr, "Input line too short.\n");
    fprintf(stderr, "Expected %zu bits - got %zu.\n", bufferSize-1, i);
    fflush(stderr);
    exit(1);
  }

  /* Check that the line ends with a newline character */
  if (i == bufferSize-1 && c != '\n' && c != EOF) {
    fprintf(stderr, "Input line too long.\n");
    fprintf(stderr, "Expected %zu bits followed by '\\n'.\n", bufferSize-1);
    exit(1);
  }

  return 0;
}

unsigned char rom0[16][7] = {
  {1, 0, 1, 1, 1, 1, 1}, {0, 0, 0, 0, 1, 1, 0}, {0, 1, 1, 1, 0, 1, 1},
  {0, 1, 0, 1, 1, 1, 1}, {1, 1, 0, 0, 1, 1, 0}, {1, 1, 0, 1, 1, 0, 1},
  {1, 1, 1, 1, 1, 0, 1}, {0, 0, 0, 0, 1, 1, 1}, {1, 1, 1, 1, 1, 1, 1},
  {1, 1, 0, 1, 1, 1, 1}, {0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0}};

void call_rom0(unsigned char e0, unsigned char e1, unsigned char e2,
               unsigned char e3, unsigned char *s0, unsigned char *s1,
               unsigned char *s2, unsigned char *s3, unsigned char *s4,
               unsigned char *s5, unsigned char *s6) {
  int index = e0 + 2 * e1 + 4 * e2 + 8 * e3;
  *s0 = rom0[index][0];
  *s1 = rom0[index][1];
  *s2 = rom0[index][2];
  *s3 = rom0[index][3];
  *s4 = rom0[index][4];
  *s5 = rom0[index][5];
  *s6 = rom0[index][6];
}

unsigned char rom1[32][8] = {
  {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 1},
  {0, 0, 0, 0, 0, 0, 1, 0}, {0, 0, 0, 0, 0, 0, 1, 1},
  {0, 0, 0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 0, 1, 0, 1},
  {0, 0, 0, 0, 0, 1, 1, 0}, {0, 0, 0, 0, 0, 1, 1, 1},
  {0, 0, 0, 0, 1, 0, 0, 0}, {0, 0, 0, 0, 1, 0, 0, 1},
  {0, 0, 0, 1, 0, 0, 0, 0}, {0, 0, 0, 1, 0, 0, 0, 1},
  {0, 0, 0, 1, 0, 0, 1, 0}, {0, 0, 0, 1, 0, 0, 1, 1},
  {0, 0, 0, 1, 0, 1, 0, 0}, {0, 0, 0, 1, 0, 1, 0, 1},
  {0, 0, 0, 1, 0, 1, 1, 0}, {0, 0, 0, 1, 0, 1, 1, 1},
  {0, 0, 0, 1, 1, 0, 0, 0}, {0, 0, 0, 1, 1, 0, 0, 1},
  {0, 0, 1, 0, 0, 0, 0, 0}, {0, 0, 1, 0, 0, 0, 0, 1},
  {0, 0, 1, 0, 0, 0, 1, 0}, {0, 0, 1, 0, 0, 0, 1, 1},
  {0, 0, 1, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}};

void call_rom1(unsigned char e0, unsigned char e1, unsigned char e2,
               unsigned char e3, unsigned char e4, unsigned char *s0,
               unsigned char *s1, unsigned char *s2, unsigned char *s3,
               unsigned char *s4, unsigned char *s5, unsigned char *s6,
               unsigned char *s7) {
  int index = e0 + 2 * e1 + 4 * e2 + 8 * e3 + 16 * e4;
  *s0 = rom1[index][0];
  *s1 = rom1[index][1];
  *s2 = rom1[index][2];
  *s3 = rom1[index][3];
  *s4 = rom1[index][4];
  *s5 = rom1[index][5];
  *s6 = rom1[index][6];
  *s7 = rom1[index][7];
}

unsigned char input_string[2];

void input(unsigned char *e0) {
  readLineFromStdin(input_string, 2);
  *e0 = (input_string[0] == '1');
}

char output_string[43] = "000000000000000000000000000000000000000000";

void output(unsigned char e0, unsigned char e1, unsigned char e2,
            unsigned char e3, unsigned char e4, unsigned char e5,
            unsigned char e6, unsigned char e7, unsigned char e8,
            unsigned char e9, unsigned char e10, unsigned char e11,
            unsigned char e12, unsigned char e13, unsigned char e14,
            unsigned char e15, unsigned char e16, unsigned char e17,
            unsigned char e18, unsigned char e19, unsigned char e20,
            unsigned char e21, unsigned char e22, unsigned char e23,
            unsigned char e24, unsigned char e25, unsigned char e26,
            unsigned char e27, unsigned char e28, unsigned char e29,
            unsigned char e30, unsigned char e31, unsigned char e32,
            unsigned char e33, unsigned char e34, unsigned char e35,
            unsigned char e36, unsigned char e37, unsigned char e38,
            unsigned char e39, unsigned char e40, unsigned char e41) {
  output_string[0] = e0 ? '1' : '0';
  output_string[1] = e1 ? '1' : '0';
  output_string[2] = e2 ? '1' : '0';
  output_string[3] = e3 ? '1' : '0';
  output_string[4] = e4 ? '1' : '0';
  output_string[5] = e5 ? '1' : '0';
  output_string[6] = e6 ? '1' : '0';
  output_string[7] = e7 ? '1' : '0';
  output_string[8] = e8 ? '1' : '0';
  output_string[9] = e9 ? '1' : '0';
  output_string[10] = e10 ? '1' : '0';
  output_string[11] = e11 ? '1' : '0';
  output_string[12] = e12 ? '1' : '0';
  output_string[13] = e13 ? '1' : '0';
  output_string[14] = e14 ? '1' : '0';
  output_string[15] = e15 ? '1' : '0';
  output_string[16] = e16 ? '1' : '0';
  output_string[17] = e17 ? '1' : '0';
  output_string[18] = e18 ? '1' : '0';
  output_string[19] = e19 ? '1' : '0';
  output_string[20] = e20 ? '1' : '0';
  output_string[21] = e21 ? '1' : '0';
  output_string[22] = e22 ? '1' : '0';
  output_string[23] = e23 ? '1' : '0';
  output_string[24] = e24 ? '1' : '0';
  output_string[25] = e25 ? '1' : '0';
  output_string[26] = e26 ? '1' : '0';
  output_string[27] = e27 ? '1' : '0';
  output_string[28] = e28 ? '1' : '0';
  output_string[29] = e29 ? '1' : '0';
  output_string[30] = e30 ? '1' : '0';
  output_string[31] = e31 ? '1' : '0';
  output_string[32] = e32 ? '1' : '0';
  output_string[33] = e33 ? '1' : '0';
  output_string[34] = e34 ? '1' : '0';
  output_string[35] = e35 ? '1' : '0';
  output_string[36] = e36 ? '1' : '0';
  output_string[37] = e37 ? '1' : '0';
  output_string[38] = e38 ? '1' : '0';
  output_string[39] = e39 ? '1' : '0';
  output_string[40] = e40 ? '1' : '0';
  output_string[41] = e41 ? '1' : '0';
  fprintf(stdout, "%s\n", output_string);
  fflush(stdout);
}

unsigned char s_0_0, s_1_0, s_2_0, s_3_0, s_4_0, s_5_0, s_6_0, s_7_0, s_8_0,
  s_9_0, s_10_0, s_11_0, s_12_0, s_13_0, s_14_0, s_15_0, s_16_0, s_17_0,
  s_18_0, s_19_0, s_20_0, s_21_0, s_22_0, s_23_0, s_24_0, s_25_0, s_26_0,
  s_27_0, s_28_0, s_29_0, s_30_0, s_31_0, s_32_0, s_33_0, s_34_0, s_35_0,
  s_37_0, s_38_0, s_39_0, s_40_0, s_41_0, s_42_0, s_43_0, s_44_0, s_45_0,
  s_46_0, s_47_0, s_48_0, s_49_0, s_50_0, s_51_0, s_52_0, s_53_0, s_54_0,
  s_55_0, s_56_0, s_58_0, s_60_0, s_62_0, s_64_0, s_64_1, s_64_2, s_64_3,
  s_64_4, s_64_5, s_64_6, s_65_0, s_66_0, s_67_0, s_68_0, s_69_0, s_70_0,
  s_71_0, s_72_0, s_73_0, s_74_0, s_75_0, s_76_0, s_77_0, s_78_0, s_79_0,
  s_80_0, s_82_0, s_84_0, s_86_0, s_86_1, s_86_2, s_86_3, s_86_4, s_86_5,
  s_86_6, s_87_0, s_88_0, s_89_0, s_90_0, s_91_0, s_92_0, s_93_0, s_94_0,
  s_95_0, s_96_0, s_97_0, s_98_0, s_99_0, s_100_0, s_101_0, s_102_0, s_103_0,
  s_104_0, s_105_0, s_106_0, s_108_0, s_110_0, s_112_0, s_114_0, s_114_1,
  s_114_2, s_114_3, s_114_4, s_114_5, s_114_6, s_115_0, s_116_0, s_117_0,
  s_118_0, s_119_0, s_120_0, s_121_0, s_122_0, s_123_0, s_124_0, s_125_0,
  s_126_0, s_127_0, s_128_0, s_129_0, s_130_0, s_132_0, s_134_0, s_136_0,
  s_136_1, s_136_2, s_136_3, s_136_4, s_136_5, s_136_6, s_137_0, s_138_0,
  s_139_0, s_140_0, s_141_0, s_142_0, s_143_0, s_144_0, s_145_0, s_145_1,
  s_145_2, s_145_3, s_145_4, s_145_5, s_145_6, s_145_7, s_146_0, s_146_1,
  s_146_2, s_146_3, s_146_4, s_146_5, s_146_6, s_147_0, s_147_1, s_147_2,
  s_147_3, s_147_4, s_147_5, s_147_6, s_149_0, s_150_0, s_151_0, s_152_0,
  s_153_0, s_154_0, s_155_0, s_156_0, s_157_0, s_158_0, s_159_0, s_160_0,
  s_161_0, s_162_0, s_164_0, s_166_0, s_168_0, s_170_0;

int main(int argc, char **argv) {
  int ncy = 1, index_cy = 0, r = 0;
  if (argc > 1) r = sscanf(argv[1], "%d", &ncy);
  s_29_0 = 0;
  s_43_0 = 0;
  s_41_0 = 0;
  s_38_0 = 0;
  s_37_0 = 0;
  s_69_0 = 0;
  s_67_0 = 0;
  s_65_0 = 0;
  s_93_0 = 0;
  s_91_0 = 0;
  s_88_0 = 0;
  s_87_0 = 0;
  s_119_0 = 0;
  s_117_0 = 0;
  s_115_0 = 0;
  s_144_0 = 0;
  s_143_0 = 0;
  s_141_0 = 0;
  s_138_0 = 0;
  s_137_0 = 0;
  while (index_cy < ncy) {
    if (r) index_cy++;
    input(&s_0_0);
    s_1_0 = 0;
    s_2_0 = 0;
    s_3_0 = 0;
    s_4_0 = 1;
    s_5_0 = 0;
    s_6_0 = s_4_0;
    s_7_0 = 0;
    s_8_0 = 0;
    s_9_0 = 0;
    s_10_0 = 0;
    s_11_0 = 0;
    s_12_0 = 0;
    s_13_0 = 0;
    s_14_0 = 0;
    s_15_0 = 0;
    s_16_0 = 0;
    s_17_0 = 0;
    s_18_0 = 0;
    s_19_0 = 0;
    s_20_0 = 0;
    s_21_0 = 0;
    s_22_0 = 0;
    s_23_0 = 0;
    s_24_0 = 0;
    s_25_0 = 0;
    s_26_0 = 0;
    s_27_0 = 0;
    s_28_0 = 0;
    s_30_0 = s_29_0 && s_6_0;
    s_31_0 = s_30_0;
    s_32_0= s_1_0 || s_31_0;
    s_33_0 = s_32_0;
    s_34_0 = s_29_0 ? !s_6_0 : s_6_0;
    s_35_0 = s_5_0 ? s_7_0 : s_34_0;
    s_39_0 = !s_38_0;
    s_40_0 = s_39_0 && s_37_0;
    s_42_0 = !s_41_0;
    s_44_0 = s_43_0 && s_33_0;
    s_45_0 = s_41_0 && s_44_0;
    s_46_0 = s_38_0 && s_45_0;
    s_47_0 = s_37_0 && s_46_0;
    s_48_0 = s_37_0 ? !s_46_0 : s_46_0;
    s_49_0 = s_38_0 ? !s_45_0 : s_45_0;
    s_50_0 = s_41_0 ? !s_44_0 : s_44_0;
    s_51_0 = s_43_0 ? !s_33_0 : s_33_0;
    s_52_0 = s_43_0 && s_42_0;
    s_53_0 = s_52_0 && s_40_0;
    s_54_0 = s_32_0 && s_53_0;
    s_55_0 = s_54_0;
    s_56_0 = s_54_0 ? s_11_0 : s_51_0;
    s_58_0 = s_54_0 ? s_10_0 : s_50_0;
    s_60_0 = s_54_0 ? s_9_0 : s_49_0;
    s_62_0 = s_54_0 ? s_8_0 : s_48_0;
    call_rom0(s_43_0, s_41_0, s_38_0, s_37_0, &s_64_0, &s_64_1, &s_64_2,
              &s_64_3, &s_64_4, &s_64_5, &s_64_6);
    s_66_0 = s_54_0 && s_65_0;
    s_68_0 = !s_67_0;
    s_70_0 = s_69_0 && s_55_0;
    s_71_0 = s_67_0 && s_70_0;
    s_72_0 = s_65_0 && s_71_0;
    s_73_0 = s_65_0 ? !s_71_0 : s_71_0;
    s_74_0 = s_67_0 ? !s_70_0 : s_70_0;
    s_75_0 = s_69_0 ? !s_55_0 : s_55_0;
    s_76_0 = s_68_0 && s_69_0;
    s_77_0 = s_66_0 && s_76_0;
    s_78_0= s_2_0 || s_77_0;
    s_79_0 = s_78_0;
    s_80_0 = s_77_0 ? s_14_0 : s_75_0;
    s_82_0 = s_77_0 ? s_13_0 : s_74_0;
    s_84_0 = s_77_0 ? s_12_0 : s_73_0;
    call_rom0(s_69_0, s_67_0, s_65_0, s_15_0, &s_86_0, &s_86_1, &s_86_2,
              &s_86_3, &s_86_4, &s_86_5, &s_86_6);
    s_89_0 = !s_88_0;
    s_90_0 = s_89_0 && s_87_0;
    s_92_0 = !s_91_0;
    s_94_0 = s_93_0 && s_79_0;
    s_95_0 = s_91_0 && s_94_0;
    s_96_0 = s_88_0 && s_95_0;
    s_97_0 = s_87_0 && s_96_0;
    s_98_0 = s_87_0 ? !s_96_0 : s_96_0;
    s_99_0 = s_88_0 ? !s_95_0 : s_95_0;
    s_100_0 = s_91_0 ? !s_94_0 : s_94_0;
    s_101_0 = s_93_0 ? !s_79_0 : s_79_0;
    s_102_0 = s_93_0 && s_92_0;
    s_103_0 = s_102_0 && s_90_0;
    s_104_0 = s_78_0 && s_103_0;
    s_105_0 = s_104_0;
    s_106_0 = s_104_0 ? s_19_0 : s_101_0;
    s_108_0 = s_104_0 ? s_18_0 : s_100_0;
    s_110_0 = s_104_0 ? s_17_0 : s_99_0;
    s_112_0 = s_104_0 ? s_16_0 : s_98_0;
    call_rom0(s_93_0, s_91_0, s_88_0, s_87_0, &s_114_0, &s_114_1, &s_114_2,
              &s_114_3, &s_114_4, &s_114_5, &s_114_6);
    s_116_0 = s_104_0 && s_115_0;
    s_118_0 = !s_117_0;
    s_120_0 = s_119_0 && s_105_0;
    s_121_0 = s_117_0 && s_120_0;
    s_122_0 = s_115_0 && s_121_0;
    s_123_0 = s_115_0 ? !s_121_0 : s_121_0;
    s_124_0 = s_117_0 ? !s_120_0 : s_120_0;
    s_125_0 = s_119_0 ? !s_105_0 : s_105_0;
    s_126_0 = s_118_0 && s_119_0;
    s_127_0 = s_116_0 && s_126_0;
    s_128_0= s_3_0 || s_127_0;
    s_129_0 = s_128_0;
    s_130_0 = s_127_0 ? s_22_0 : s_125_0;
    s_132_0 = s_127_0 ? s_21_0 : s_124_0;
    s_134_0 = s_127_0 ? s_20_0 : s_123_0;
    call_rom0(s_119_0, s_117_0, s_115_0, s_23_0, &s_136_0, &s_136_1,
              &s_136_2, &s_136_3, &s_136_4, &s_136_5, &s_136_6);
    s_139_0 = !s_138_0;
    s_140_0 = s_139_0 && s_128_0;
    s_142_0 = s_137_0 && s_141_0;
    call_rom1(s_144_0, s_143_0, s_141_0, s_138_0, s_137_0, &s_145_0,
              &s_145_1, &s_145_2, &s_145_3, &s_145_4, &s_145_5, &s_145_6,
              &s_145_7);
    call_rom0(s_145_7, s_145_6, s_145_5, s_145_4, &s_146_0, &s_146_1,
              &s_146_2, &s_146_3, &s_146_4, &s_146_5, &s_146_6);
    call_rom0(s_145_3, s_145_2, s_145_1, s_145_0, &s_147_0, &s_147_1,
              &s_147_2, &s_147_3, &s_147_4, &s_147_5, &s_147_6);
    output(s_147_0, s_147_1, s_147_2, s_147_3, s_147_4, s_147_5, s_147_6,
           s_146_0, s_146_1, s_146_2, s_146_3, s_146_4, s_146_5, s_146_6,
           s_136_0, s_136_1, s_136_2, s_136_3, s_136_4, s_136_5, s_136_6,
           s_114_0, s_114_1, s_114_2, s_114_3, s_114_4, s_114_5, s_114_6,
           s_86_0, s_86_1, s_86_2, s_86_3, s_86_4, s_86_5, s_86_6, s_64_0,
           s_64_1, s_64_2, s_64_3, s_64_4, s_64_5, s_64_6);
    s_149_0 = s_144_0 && s_129_0;
    s_150_0 = s_143_0 && s_149_0;
    s_151_0 = s_141_0 && s_150_0;
    s_152_0 = s_138_0 && s_151_0;
    s_153_0 = s_137_0 && s_152_0;
    s_154_0 = s_137_0 ? !s_152_0 : s_152_0;
    s_155_0 = s_138_0 ? !s_151_0 : s_151_0;
    s_156_0 = s_141_0 ? !s_150_0 : s_150_0;
    s_157_0 = s_143_0 ? !s_149_0 : s_149_0;
    s_158_0 = s_144_0 ? !s_129_0 : s_129_0;
    s_159_0 = s_143_0 && s_144_0;
    s_160_0 = s_142_0 && s_159_0;
    s_161_0 = s_160_0 && s_140_0;
    s_162_0 = s_161_0 ? s_28_0 : s_158_0;
    s_164_0 = s_161_0 ? s_27_0 : s_157_0;
    s_166_0 = s_161_0 ? s_26_0 : s_156_0;
    s_168_0 = s_161_0 ? s_25_0 : s_155_0;
    s_170_0 = s_161_0 ? s_24_0 : s_154_0;
    /* Update registers. */
    s_29_0 = s_35_0;
    s_43_0 = s_56_0;
    s_41_0 = s_58_0;
    s_38_0 = s_60_0;
    s_37_0 = s_62_0;
    s_69_0 = s_80_0;
    s_67_0 = s_82_0;
    s_65_0 = s_84_0;
    s_93_0 = s_106_0;
    s_91_0 = s_108_0;
    s_88_0 = s_110_0;
    s_87_0 = s_112_0;
    s_119_0 = s_130_0;
    s_117_0 = s_132_0;
    s_115_0 = s_134_0;
    s_144_0 = s_162_0;
    s_143_0 = s_164_0;
    s_141_0 = s_166_0;
    s_138_0 = s_168_0;
    s_137_0 = s_170_0;
  }
  return(0);
}
