Example of get_date invocations.

  $ ./get_date.exe 23:59:50 1999/12/31
  // Initial memory contents for Visa
  // Generated by: ./get_date.exe '23:59:50' '1999/12/31'
  sec: 01001100
  min: 11011100
  hou: 11101000
  day: 01111000
  mon: 11010000
  yea: 11000110
