Example of get_date invocations.

  $ ./get_date.exe 23:59:50 1999/12/31
  // Initial memory contents for Visa
  // Generated by: ./get_date.exe '23:59:50' '1999/12/31'
  01001100 // sec
  11011100 // min
  11101000 // hou
  01111000 // day
  11010000 // mon
  11000110 // yea
