name: build-odoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build odoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install sdl2 dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-image-dev

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1.x
          dune-cache: true
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            mbarbin: https://github.com/mbarbin/opam-repository.git

      - run: opam install . --deps-only --with-doc
        shell: bash

      - run: opam depext --install odoc
        shell: bash

      - run: opam exec -- dune build @doc
        shell: bash

      - name: Lint doc
        uses: ocaml/setup-ocaml/lint-doc@v2
