/* Program generated by bop2c */
/* Original circuit : empty.bop , Main = "Main" */

#include <stdlib.h>
#include <stdio.h>

/* Reads a line of text from standard input into a buffer of given size.
   Returns 0 on success, and exit 1 on error. */
int readLineFromStdin(char* buffer, size_t bufferSize) {
  /* Read a line of text from standard input into the buffer. */
  size_t i = 0;
  int c = getchar();
  while (i < bufferSize-1 && c != '\n' && c != EOF) {
    buffer[i] = (char)c;
    i++;
    c = getchar();
  }
  buffer[i] = '\0';

  if (i == 0 && c == EOF) {
    exit(0);
  }

  if (i < bufferSize-1) {
    fprintf(stderr, "Input line too short.\n");
    fprintf(stderr, "Expected %zu bits - got %zu.\n", bufferSize-1, i);
    fflush(stderr);
    exit(1);
  }

  /* Check that the line ends with a newline character */
  if (i == bufferSize-1 && c != '\n' && c != EOF) {
    fprintf(stderr, "Input line too long.\n");
    fprintf(stderr, "Expected %zu bits followed by '\\n'.\n", bufferSize-1);
    exit(1);
  }

  return 0;
}

unsigned char input_string[1];

void input() {
  readLineFromStdin(input_string, 1);
}

char output_string[1] = "";

void output() {
  fprintf(stdout, "%s\n", output_string);
  fflush(stdout);
}

int main(int argc, char **argv) {
  int ncy = 1, index_cy = 0, r = 0;
  if (argc > 1) r = sscanf(argv[1], "%d", &ncy);
  while (index_cy < ncy) {
    if (r) index_cy++;
    input();
    output();
  }
  return(0);
}
