/* Program generated by bop2c */
/* Original circuit : hello_ram.bop , Main = "Main" */

#include <stdlib.h>
#include <stdio.h>

/* Reads a line of text from standard input into a buffer of given size.
   Returns 0 on success, and exit 1 on error. */
int readLineFromStdin(char* buffer, size_t bufferSize) {
  /* Read a line of text from standard input into the buffer. */
  size_t i = 0;
  int c = getchar();
  while (i < bufferSize-1 && c != '\n' && c != EOF) {
    buffer[i] = (char)c;
    i++;
    c = getchar();
  }
  buffer[i] = '\0';

  if (i == 0 && c == EOF) {
    exit(0);
  }

  if (i < bufferSize-1) {
    fprintf(stderr, "Input line too short.\n");
    fprintf(stderr, "Expected %zu bits - got %zu.\n", bufferSize-1, i);
    fflush(stderr);
    exit(1);
  }

  /* Check that the line ends with a newline character */
  if (i == bufferSize-1 && c != '\n' && c != EOF) {
    fprintf(stderr, "Input line too long.\n");
    fprintf(stderr, "Expected %zu bits followed by '\\n'.\n", bufferSize-1);
    exit(1);
  }

  return 0;
}

unsigned char ram0[4][4] = {
  {0, 0, 0, 1}, {0, 0, 1, 0}, {0, 1, 0, 0}, {1, 0, 0, 0}};

void call_ram0(unsigned char r0, unsigned char r1, unsigned char e0,
               unsigned char e1, unsigned char en, unsigned char d0,
               unsigned char d1, unsigned char d2, unsigned char d3,
               unsigned char *s0, unsigned char *s1, unsigned char *s2,
               unsigned char *s3) {
  int index;
  if (en) {
    index = e0 + 2 * e1;
    ram0[index][0] = d0;
    ram0[index][1] = d1;
    ram0[index][2] = d2;
    ram0[index][3] = d3;
  } else {
    index = r0 + 2 * r1;
    *s0 = ram0[index][0];
    *s1 = ram0[index][1];
    *s2 = ram0[index][2];
    *s3 = ram0[index][3];
  }
}

unsigned char input_string[10];

void input(unsigned char *e0, unsigned char *e1, unsigned char *e2,
           unsigned char *e3, unsigned char *e4, unsigned char *e5,
           unsigned char *e6, unsigned char *e7, unsigned char *e8) {
  readLineFromStdin(input_string, 10);
  *e0 = (input_string[0] == '1');
  *e1 = (input_string[1] == '1');
  *e2 = (input_string[2] == '1');
  *e3 = (input_string[3] == '1');
  *e4 = (input_string[4] == '1');
  *e5 = (input_string[5] == '1');
  *e6 = (input_string[6] == '1');
  *e7 = (input_string[7] == '1');
  *e8 = (input_string[8] == '1');
}

char output_string[5] = "0000";

void output(unsigned char e0, unsigned char e1, unsigned char e2,
            unsigned char e3) {
  output_string[0] = e0 ? '1' : '0';
  output_string[1] = e1 ? '1' : '0';
  output_string[2] = e2 ? '1' : '0';
  output_string[3] = e3 ? '1' : '0';
  fprintf(stdout, "%s\n", output_string);
  fflush(stdout);
}

unsigned char s_0_0, s_0_1, s_0_2, s_0_3, s_0_4, s_0_5, s_0_6, s_0_7, s_0_8,
  s_1_0, s_2_0, s_3_0, s_4_0, s_5_0, s_5_1, s_5_2, s_5_3, s_6_0, s_7_0,
  s_8_0, s_9_0;

int main(int argc, char **argv) {
  int ncy = 1, index_cy = 0, r = 0;
  if (argc > 1) r = sscanf(argv[1], "%d", &ncy);
  while (index_cy < ncy) {
    if (r) index_cy++;
    input(&s_0_0, &s_0_1, &s_0_2, &s_0_3, &s_0_4, &s_0_5, &s_0_6, &s_0_7,
          &s_0_8);
    s_1_0 = 0;
    s_2_0 = 0;
    s_3_0 = 0;
    s_4_0 = 0;
    call_ram0(s_0_0, s_0_1, s_0_2, s_0_3, s_0_4, s_0_5, s_0_6, s_0_7, s_0_8,
              &s_5_0, &s_5_1, &s_5_2, &s_5_3);
    s_6_0 = s_0_4 ? s_4_0 : s_5_3;
    s_7_0 = s_0_4 ? s_3_0 : s_5_2;
    s_8_0 = s_0_4 ? s_2_0 : s_5_1;
    s_9_0 = s_0_4 ? s_1_0 : s_5_0;
    output(s_9_0, s_8_0, s_7_0, s_6_0);
  }
  return(0);
}
