/* Program generated by bop2c */
/* Original circuit : hello_register.bop , Main = "Main" */

#include <stdlib.h>
#include <stdio.h>

/* Reads a line of text from standard input into a buffer of given size.
   Returns 0 on success, and exit 1 on error. */
int readLineFromStdin(char* buffer, size_t bufferSize) {
  /* Read a line of text from standard input into the buffer. */
  size_t i = 0;
  int c = getchar();
  while (i < bufferSize-1 && c != '\n' && c != EOF) {
    buffer[i] = (char)c;
    i++;
    c = getchar();
  }
  buffer[i] = '\0';

  if (i == 0 && c == EOF) {
    exit(0);
  }

  if (i < bufferSize-1) {
    fprintf(stderr, "Input line too short.\n");
    fprintf(stderr, "Expected %zu bits - got %zu.\n", bufferSize-1, i);
    fflush(stderr);
    exit(1);
  }

  /* Check that the line ends with a newline character */
  if (i == bufferSize-1 && c != '\n' && c != EOF) {
    fprintf(stderr, "Input line too long.\n");
    fprintf(stderr, "Expected %zu bits followed by '\\n'.\n", bufferSize-1);
    exit(1);
  }

  return 0;
}

unsigned char input_string[2];

void input(unsigned char *e0) {
  readLineFromStdin(input_string, 2);
  *e0 = (input_string[0] == '1');
}

char output_string[5] = "0000";

void output(unsigned char e0, unsigned char e1, unsigned char e2,
            unsigned char e3) {
  output_string[0] = e0 ? '1' : '0';
  output_string[1] = e1 ? '1' : '0';
  output_string[2] = e2 ? '1' : '0';
  output_string[3] = e3 ? '1' : '0';
  fprintf(stdout, "%s\n", output_string);
  fflush(stdout);
}

unsigned char s_0_0, s_1_0, s_2_0, s_4_0, s_5_0, s_7_0, s_8_0, s_10_0,
  s_12_0;

int main(int argc, char **argv) {
  int ncy = 1, index_cy = 0, r = 0;
  if (argc > 1) r = sscanf(argv[1], "%d", &ncy);
  s_1_0 = 0;
  s_4_0 = 1;
  s_7_0 = 0;
  s_10_0 = 1;
  while (index_cy < ncy) {
    if (r) index_cy++;
    input(&s_0_0);
    s_2_0 = !s_1_0;
    s_5_0 = !s_4_0;
    s_8_0 = !s_7_0;
    output(s_1_0, s_4_0, s_7_0, s_10_0);
    s_12_0 = !s_10_0;
    /* Update registers. */
    s_1_0 = s_2_0;
    s_4_0 = s_5_0;
    if (s_0_0) s_7_0 = s_8_0;
    if (s_0_0) s_10_0 = s_12_0;
  }
  return(0);
}
